<?php
require_once __DIR__ . '/demo_image_loader.php';

/**
 * Каталог демо-изображений (Unsplash) и тексты акций/новостей.
 */
function demoImageCatalog(array $forceKeys = []): array
{
    $q = 'w=960&q=82&auto=format&fit=crop';

    return demoPrepareImageCatalog([
        'park_cleanup' => [
            'file' => 'assets/images/demo/events/park-cleanup.jpg',
            'url' => "https://images.unsplash.com/photo-1532996122724-e3c751a69200?{$q}",
        ],
        'dog_shelter' => [
            'file' => 'assets/images/demo/events/dog-shelter.jpg',
            'url' => "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?{$q}",
        ],
        'senior_tablet' => [
            'file' => 'assets/images/demo/events/senior-tablet.jpg',
            'url' => "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?{$q}",
        ],
        'tree_planting' => [
            'file' => 'assets/images/demo/events/tree-planting.jpg',
            'url' => "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?{$q}",
        ],
        'blood_donation' => [
            'file' => 'assets/images/demo/events/blood-donation.jpg',
            'url' => "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?{$q}",
        ],
        'festival' => [
            'file' => 'assets/images/demo/events/festival.jpg',
            'url' => "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?{$q}",
        ],
        'lake_cleanup' => [
            'file' => 'assets/images/demo/events/lake-cleanup.jpg',
            'url' => "https://images.unsplash.com/photo-1559827260-dc66d52bef19?{$q}",
        ],
        'river_cleanup' => [
            'file' => 'assets/images/demo/events/river-cleanup.jpg',
            'url' => "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?{$q}",
        ],
        'cat_shelter' => [
            'file' => 'assets/images/demo/events/cat-shelter.jpg',
            'url' => "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?{$q}",
        ],
        'soup_kitchen' => [
            'file' => 'assets/images/demo/events/soup-kitchen.jpg',
            'url' => "https://images.unsplash.com/photo-1556910103-1c02745aae4d?{$q}",
        ],
        'library_kids' => [
            'file' => 'assets/images/demo/events/library-kids.jpg',
            'url' => "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?{$q}",
        ],
        'clothes_sorting' => [
            'file' => 'assets/images/demo/events/clothes-sorting.jpg',
            'url' => "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?{$q}",
        ],
        'first_aid' => [
            'file' => 'assets/images/demo/events/first-aid.jpg',
            'url' => "https://images.unsplash.com/photo-1582750433449-648ed127bb54?{$q}",
        ],
        'concert' => [
            'file' => 'assets/images/demo/events/concert.jpg',
            'url' => "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?{$q}",
        ],
        'recycling' => [
            'file' => 'assets/images/demo/events/recycling.jpg',
            'url' => "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?{$q}",
        ],
        'volunteers_team' => [
            'file' => 'assets/images/demo/news/volunteers-team.jpg',
            'url' => "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?{$q}",
        ],
        'news_park' => [
            'file' => 'assets/images/demo/news/news-park.jpg',
            'url' => "https://images.unsplash.com/photo-1497436072904-60f360e1d4b1?{$q}",
        ],
        'news_shelter' => [
            'file' => 'assets/images/demo/news/news-shelter.jpg',
            'url' => "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?{$q}",
        ],
        'news_trees' => [
            'file' => 'assets/images/demo/news/news-trees.jpg',
            'url' => "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?{$q}",
        ],
        'news_donor' => [
            'file' => 'assets/images/demo/news/news-donor.jpg',
            'url' => "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?{$q}",
        ],
        'news_festival' => [
            'file' => 'assets/images/demo/news/news-festival.jpg',
            'url' => "https://images.unsplash.com/photo-1429962710881-bba331887704?{$q}",
        ],
        'news_lake' => [
            'file' => 'assets/images/demo/news/news-lake.jpg',
            'url' => "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?{$q}",
        ],
        'news_community' => [
            'file' => 'assets/images/demo/news/news-community.jpg',
            'url' => "https://images.unsplash.com/photo-1522071820081-009f0129c71c?{$q}",
        ],
        'news_yard' => [
            'file' => 'assets/images/demo/news/news-yard.jpg',
            'url' => "https://images.unsplash.com/photo-1581578731548-c64695cc6952?{$q}",
        ],
    ], $forceKeys);
}

function demoForceRefreshImageKeys(): array
{
    return [
        'soup_kitchen',
        'clothes_sorting',
        'tree_planting',
        'recycling',
        'blood_donation',
        'first_aid',
        'news_donor',
    ];
}

function demoEventsCatalog(): array
{
    return [
        [
            'title' => 'Уборка в парке Челюскинцев',
            'description' => 'Встречаемся у главного входа с парковой стороны. Раздадим перчатки, мешки и захваты для мелкого мусора. Планируем убрать аллеи, клумбы и зону у фонтана. После работы — чай и короткий разбор, что можно улучшить в следующий раз.',
            'category' => 'Экология',
            'creatorEmail' => 'user@test.by',
            'eventDate' => '2026-06-15 10:00:00',
            'location' => 'Минск, парк Челюскинцев, главный вход (пр. Независимости)',
            'maxParticipants' => 35,
            'isPriority' => 1,
            'imageKey' => 'park_cleanup',
            'refreshCover' => true,
        ],
        [
            'title' => 'Помощь приюту «Добрик»',
            'legacyTitles' => ['Помощь приюту "Добрик"'],
            'description' => 'Нужны волонтёры на выгул собак, мытьё мисков и уборку вольеров. Опыт с животными не обязателен — администратор покажет, как безопасно работать с питомцами. Возьмите удобную обувь и одежду, которую не жалко.',
            'category' => 'Помощь животным',
            'creatorEmail' => 'anna@test.by',
            'eventDate' => '2026-06-18 11:00:00',
            'location' => 'Минский р-н, д. Боровая, ул. Центральная, 5',
            'maxParticipants' => 10,
            'isPriority' => 1,
            'imageKey' => 'dog_shelter',
            'refreshCover' => true,
        ],
        [
            'title' => 'Обучение работе со смартфоном для пожилых',
            'description' => 'Спокойный мастер-класс для старшего поколения: установка мессенджеров, видеозвонки родным, запись к врачу и базовые правила безопасности в интернете. Ноутбуки можно взять на месте, желательно принести свой телефон.',
            'category' => 'Помощь пожилым',
            'creatorEmail' => 'user@test.by',
            'eventDate' => '2026-06-20 15:00:00',
            'location' => 'Минск, библиотека №12, ул. Каховская, 17',
            'maxParticipants' => 14,
            'isPriority' => 0,
            'imageKey' => 'senior_tablet',
            'refreshCover' => true,
        ],
        [
            'title' => 'Посадка деревьев в Лошицком парке',
            'description' => 'Совместно с администрацией парка восстановим часть аллеи после зимних повреждений. Будут лопаты, саженцы и инструктаж по посадке. Работа в лёгких перчатках, на площадке предусмотрены перерывы с водой.',
            'category' => 'Экология',
            'creatorEmail' => 'dmitry@test.by',
            'eventDate' => '2026-06-22 09:00:00',
            'location' => 'Минск, Лошицкий парк, сбор у главного входа',
            'maxParticipants' => 28,
            'isPriority' => 0,
            'imageKey' => 'tree_planting',
            'refreshCover' => true,
        ],
        [
            'title' => 'День донора в Минске',
            'description' => 'Организованная поездка в городской центр крови. Волонтёры помогают с регистрацией и сопровождением тех, кто сдаёт кровь впервые. Обязательно возьмите паспорт; лёгкий завтрак перед сдачей — по рекомендациям центра.',
            'category' => 'Донорство',
            'creatorEmail' => 'user@test.by',
            'eventDate' => '2026-06-25 08:30:00',
            'location' => 'Минск, ул. Семашко, 8 (Городской центр крови)',
            'maxParticipants' => 18,
            'isPriority' => 0,
            'imageKey' => 'blood_donation',
            'refreshCover' => true,
        ],
        [
            'title' => 'Помощь в проведении фестиваля «Волат»',
            'legacyTitles' => ['Помощь в проведении фестиваля "Волат"'],
            'description' => 'Ищем волонтёров на регистрацию гостей, навигацию по площадкам и помощь участникам. Две смены: утро и вечер. Выдадим бейдж, инструкцию и точку связи с координатором на площадке.',
            'category' => 'Культура',
            'creatorEmail' => 'anna@test.by',
            'eventDate' => '2026-07-01 09:00:00',
            'location' => 'Минск, ст. м. «Московская», вход к «Минск-Арене»',
            'maxParticipants' => 45,
            'isPriority' => 0,
            'imageKey' => 'festival',
            'refreshCover' => true,
        ],
        [
            'title' => 'Уборка на территории Минского моря',
            'description' => 'Эко-акция на берегу Заславского водохранилища: собираем пластик и мелкий мусор отдельными мешками. Маршрут около 2 км вдоль пляжной зоны. Возьмите головной убор, воду и удобную обувь.',
            'category' => 'Экология',
            'creatorEmail' => 'dmitry@test.by',
            'eventDate' => '2026-06-29 10:00:00',
            'location' => 'Заславль, пляж «Озеро» (ост. «Санаторий Юность»)',
            'maxParticipants' => 24,
            'isPriority' => 0,
            'imageKey' => 'lake_cleanup',
            'refreshCover' => false,
        ],
        [
            'title' => 'Субботник на набережной Свислочи',
            'description' => 'Приведём в порядок участок набережной от моста к Троицкому предмостью: сбор мусора, лёгкая уборка лавочек и клумб. Инвентарь выдаём на месте, работаем группами по 5–6 человек.',
            'category' => 'Экология',
            'creatorEmail' => 'user@test.by',
            'eventDate' => '2026-06-08 10:00:00',
            'location' => 'Минск, наб. Свислочи, сбор у моста на пр. Победителей',
            'maxParticipants' => 30,
            'isPriority' => 1,
            'imageKey' => 'river_cleanup',
            'refreshCover' => false,
        ],
        [
            'title' => 'Кухня добрых дел: обед для нуждающихся',
            'description' => 'Помощь в приготовлении и раздаче горячих обедов в городском пункте поддержки. Задачи: нарезка овощей, сервировка, выдача порций. Работа в сменах по 3 часа, фартуки и перчатки есть на месте.',
            'category' => 'бездомные',
            'creatorEmail' => 'anna@test.by',
            'eventDate' => '2026-06-12 11:00:00',
            'location' => 'Минск, ул. Бобруйская, 21 (пункт социальной помощи)',
            'maxParticipants' => 12,
            'isPriority' => 0,
            'imageKey' => 'soup_kitchen',
            'refreshCover' => true,
        ],
        [
            'title' => 'Читательский марафон в городской библиотеке',
            'description' => 'Помощь библиотеке в проведении детского читательского марафона: регистрация участников, чтение вслух малышам, оформление уголка с книжными рекомендациями. Подойдёт тем, кто любит работать с детьми.',
            'category' => 'Образование',
            'creatorEmail' => 'dmitry@test.by',
            'eventDate' => '2026-06-14 14:00:00',
            'location' => 'Минск, Центральная библиотека, пр. Независимости, 78',
            'maxParticipants' => 16,
            'isPriority' => 0,
            'imageKey' => 'library_kids',
            'refreshCover' => false,
        ],
        [
            'title' => 'Помощь в приюте для кошек «Мурка»',
            'description' => 'Уборка вольеров, замена наполнителя, кормление и спокойное общение с котами. Администратор расскажет, как не травмировать животных лишним шумом. Желательно без сильных ароматов духов.',
            'category' => 'Помощь животным',
            'creatorEmail' => 'anna@test.by',
            'eventDate' => '2026-06-16 12:00:00',
            'location' => 'Минск, ул. Сухаревская, 3 (вход со двора)',
            'maxParticipants' => 8,
            'isPriority' => 0,
            'imageKey' => 'cat_shelter',
            'refreshCover' => false,
        ],
        [
            'title' => 'Сортировка вещей в благотворительном магазине',
            'description' => 'Принимаем, сортируем и подготавливаем к продаже одежду и бытовые вещи. Часть выручки идёт на программы поддержки семей. Удобная одежда и терпение к монотонной работе — главное.',
            'category' => 'бездомные',
            'creatorEmail' => 'user@test.by',
            'eventDate' => '2026-06-19 10:00:00',
            'location' => 'Минск, ул. Кальварийская, 14 (магазин «Второе дыхание»)',
            'maxParticipants' => 10,
            'isPriority' => 0,
            'imageKey' => 'clothes_sorting',
            'refreshCover' => true,
        ],
        [
            'title' => 'Курс первой помощи для волонтёров',
            'description' => 'Практическое занятие с инструктором Красного Креста: остановка кровотечений, положение при обмороке, вызов скорой. Сертификат участника выдаётся в конце. Запись ограничена — мест мало.',
            'category' => 'Образование',
            'creatorEmail' => 'dmitry@test.by',
            'eventDate' => '2026-06-27 16:00:00',
            'location' => 'Минск, ул. Тимирязева, 65 (учебный класс, 2 этаж)',
            'maxParticipants' => 20,
            'isPriority' => 0,
            'imageKey' => 'first_aid',
            'refreshCover' => true,
        ],
        [
            'title' => 'Волонтёры на концерте «Звёздный вечер»',
            'description' => 'Помощь организаторам open-air концерта: контроль входа, навигация зрителей, информационная стойка. Смена 4 часа, после мероприятия — благодарность от команды фестиваля.',
            'category' => 'Культура',
            'creatorEmail' => 'anna@test.by',
            'eventDate' => '2026-07-05 17:00:00',
            'location' => 'Минск, парк Победы, открытая сцена',
            'maxParticipants' => 25,
            'isPriority' => 0,
            'imageKey' => 'concert',
            'refreshCover' => false,
        ],
        [
            'title' => 'Эко-урок в школе: раздельный сбор отходов',
            'description' => 'Проведём 45-минутный урок для 7–8 классов: что можно сдавать на переработку, как устроен раздельный сбор в городе. Нужны 4–5 волонтёров для мини-станций с образцами упаковки.',
            'category' => 'Образование',
            'creatorEmail' => 'user@test.by',
            'eventDate' => '2026-06-24 09:30:00',
            'location' => 'Минск, школа №15, ул. Якубовского, 32',
            'maxParticipants' => 6,
            'isPriority' => 0,
            'imageKey' => 'recycling',
            'refreshCover' => true,
        ],
    ];
}

function demoNewsCatalog(): array
{
    return [
        [
            'title' => 'Итоги субботника на набережной Свислочи',
            'legacyTitles' => ['Итоги субботника в парке Челюскинцев'],
            'summary' => '24 волонтёра за три часа собрали 52 мешка мусора и привели в порядок участок у моста.',
            'body' => '<p>8 июня на набережной Свислочи прошла экологическая акция. Команда работала от моста на пр. Победителей до Троицкого предмостья.</p><p>Отдельно собрали пластик и стекло — их передадим на переработку. Спасибо всем, кто вышел в будний день и помог сделать центр города чище.</p>',
            'relatedEventTitle' => 'Субботник на набережной Свислочи',
            'daysAgo' => 14,
            'imageKey' => 'news_park',
        ],
        [
            'title' => 'Приют «Добрик»: отчёт о дне помощи',
            'summary' => '11 волонтёров выгуляли 18 собак, помыли вольеры и разложили корм по секциям.',
            'body' => '<p>Суббота в приюте «Добрик» прошла насыщенно: утром распределили задачи, к обеду закончили уборку и прогулки.</p><p>Администрация приюта отметила, что регулярные выходы волонтёров заметно снижают стресс у животных. Следующая акция уже в календаре — записывайтесь заранее.</p>',
            'relatedEventTitle' => 'Помощь приюту «Добрик»',
            'daysAgo' => 13,
            'imageKey' => 'news_shelter',
        ],
        [
            'title' => 'Посадили 120 саженцев в Лошицком парке',
            'summary' => 'Совместно с администрацией парка восстановили аллею после зимних повреждений.',
            'body' => '<p>Утром встретились у главного входа, получили инструктаж и работали до обеда. Посадили липы и клёны — всего 120 саженцев.</p><p>Часть участников пришла впервые, но справились быстро благодаря подсказкам садовников парка.</p>',
            'relatedEventTitle' => 'Посадка деревьев в Лошицком парке',
            'daysAgo' => 12,
            'imageKey' => 'news_trees',
        ],
        [
            'title' => 'День донора: 14 сдач крови',
            'summary' => 'Волонтёры сопровождали доноров и помогали с регистрацией в центре трансфузиологии.',
            'body' => '<p>Акция прошла спокойно и без очередей: заранее разделили участников на группы по времени.</p><p>Четверо человек сдали кровь впервые — им выдали памятки и ответили на вопросы врача. Спасибо тем, кто нашёл время помочь незнакомым людям.</p>',
            'relatedEventTitle' => 'День донора в Минске',
            'daysAgo' => 11,
            'imageKey' => 'news_donor',
        ],
        [
            'title' => 'Фестиваль «Волат»: работа волонтёров',
            'legacyTitles' => ['Фестиваль Волат: работа волонтёров'],
            'summary' => '35 человек на регистрации и навигации — гости быстро находили нужные площадки.',
            'body' => '<p>Команда работала в две смены: утром оформили бейджи и карты площадок, вечером помогали с выходом зрителей.</p><p>Организаторы отметили, что благодаря волонтёрам время ожидания на входе сократилось почти вдвое.</p>',
            'relatedEventTitle' => 'Помощь в проведении фестиваля «Волат»',
            'daysAgo' => 10,
            'imageKey' => 'news_festival',
        ],
        [
            'title' => 'Эко-акция на Минском море завершена',
            'summary' => 'Очистили 2 км береговой линии, пластик собрали отдельно для вывоза.',
            'body' => '<p>Несмотря на ветер, участники заполнили 25 мешков. Часть мусора — бутылки и упаковка, оставленная после отдыха на пляже.</p><p>После работы устроили короткий перекус — чай и печенье привезли организаторы.</p>',
            'relatedEventTitle' => 'Уборка на территории Минского моря',
            'daysAgo' => 9,
            'imageKey' => 'news_lake',
        ],
        [
            'title' => 'Кухня добрых дел: первый выход',
            'summary' => 'Команда из 9 волонтёров приготовила и раздала 80 порций горячего обеда.',
            'body' => '<p>Утром помогли на кухне: нарезка, сервировка, выдача. Работа шла двумя сменами, чтобы не уставать.</p><p>Пункт социальной помощи поблагодарил участников и пригласил вернуться в следующий месяц.</p>',
            'relatedEventTitle' => 'Кухня добрых дел: обед для нуждающихся',
            'daysAgo' => 8,
            'imageKey' => 'soup_kitchen',
        ],
        [
            'title' => 'Читательский марафон: 40 детей за один день',
            'summary' => 'Волонтёры провели мини-квесты, чтение вслух и оформили стенд с рекомендациями.',
            'body' => '<p>Библиотека впервые провела марафон с помощью DobroHub. Дети получили наклейки за прочитанные отрывки, родители — списки книг на лето.</p><p>Организаторы планируют повторить формат осенью.</p>',
            'relatedEventTitle' => 'Читательский марафон в городской библиотеке',
            'daysAgo' => 7,
            'imageKey' => 'library_kids',
        ],
        [
            'title' => 'Новые волонтёры в DobroHub',
            'summary' => 'За месяц зарегистрировались десятки участников — добро пожаловать в сообщество!',
            'body' => '<p>После регистрации можно сразу записываться на акции в каталоге. Напоминаем: организаторы видят ваши контакты только после подтверждения записи.</p><p>Если хотите предложить свою акцию — форма доступна в личном кабинете после входа.</p>',
            'relatedEventTitle' => null,
            'daysAgo' => 6,
            'imageKey' => 'news_community',
        ],
        [
            'title' => 'Как предложить свою акцию',
            'summary' => 'Краткая инструкция для организаторов: заполните форму и дождитесь проверки модератором.',
            'body' => '<p>Укажите место, дату, описание и лимит участников. После одобрения акция появится в каталоге, а вы получите доступ к списку записавшихся.</p><p>Модерация обычно занимает 1–2 рабочих дня. Если акцию отклонили — в карточке будет указана причина.</p>',
            'relatedEventTitle' => null,
            'daysAgo' => 5,
            'imageKey' => 'volunteers_team',
        ],
        [
            'title' => 'Итоги весенней недели добрых дел',
            'summary' => 'Экология, помощь пожилым и работа на мероприятиях — короткий обзор нескольких акций.',
            'body' => '<p>За неделю прошло пять акций в разных районах города. Больше всего участников собрала уборка в парке и помощь в приюте.</p><p>Спасибо всем, кто находил время помогать. Новые даты уже в каталоге — загляните в раздел «Каталог акций».</p>',
            'relatedEventTitle' => null,
            'daysAgo' => 4,
            'imageKey' => 'news_park',
        ],
        [
            'title' => 'Субботник во дворе: мини-отчёт',
            'summary' => 'Жители и волонтёры прибрали детскую площадку и клумбы — результат виден сразу.',
            'body' => '<p>Работа заняла три часа. Мусор вывезли совместно с управляющей компанией, клумбы подкормили и полили.</p><p>Такие локальные акции можно предложить через DobroHub — соседи часто быстро откликаются.</p>',
            'relatedEventTitle' => null,
            'daysAgo' => 3,
            'imageKey' => 'news_yard',
        ],
        [
            'title' => 'Благодарность участникам мая',
            'summary' => 'Отдельное спасибо тем, кто выходил на акции в будни и помогал с организацией.',
            'body' => '<p>Ваш вклад делает город чище, а людям вокруг — спокойнее. Особенно ценим тех, кто приходит регулярно и подхватывает задачи без напоминаний.</p><p>До встречи на новых акциях!</p>',
            'relatedEventTitle' => null,
            'daysAgo' => 2,
            'imageKey' => 'volunteers_team',
        ],
        [
            'title' => 'Мастер-класс для пожилых: учимся видеозвонкам',
            'summary' => '12 участников за два часа освоили WhatsApp и видеосвязь с родными.',
            'body' => '<p>Занятие прошло в библиотеке №12. Разобрали установку приложений, добавление контактов и безопасность — не переходить по незнакомым ссылкам.</p><p>Несколько человек сразу позвонили родственникам прямо с занятия — это лучший результат.</p>',
            'relatedEventTitle' => 'Обучение работе со смартфоном для пожилых',
            'daysAgo' => 1,
            'imageKey' => 'senior_tablet',
        ],
    ];
}
